### Create new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "hello@qwerty.com",
  "password": "asdfghjkl"
}

### Find a user by id
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email=hello@canada.com

### Delete user by id
DELETE http://localhost:3000/auth/0

###Update a user
PATCH http://localhost:3000/auth/1000
content-type: application/json

{
  "password": "lkjhgf"
}